{
 "title": "Spark Operator",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Spark_Operator_Instance",
    "label": "Spark Operator Instance",
    "query": {
     "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=\"spark-operator\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SparkApplication and Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Submitted SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication submitted by the Operator.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_submit_count{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication which failed to complete.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_failure_count{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Running SparkApplications",
   "type": "singlestat",
   "description": "Total number of SparkApplication which are currently running.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_running_count{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which failed.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_failure_count{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succ. completed SparkApplications.",
   "type": "singlestat",
   "description": "Total number of SparkApplication which completed successfully.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_success_count{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succ. Completed Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which completed successfully.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_success_count{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Running Spark Executors",
   "type": "singlestat",
   "description": "Total number of Spark Executors which are currently running.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_executor_running_count{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  { "title": "SparkApplication Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Adds handled by work queue",
   "type": "singlestat",
   "description": "Total number of adds handled by work queue",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_adds{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "spark_application_controller_depth{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "singlestat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_retries{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "singlestat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_unfinished_work_seconds{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "singlestat",
   "description": "Longest running processor in microseconds",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_longest_running_processor_microseconds{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "ScheduledApplication Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Adds handled by work queue",
   "type": "singlestat",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_adds{pod=\"$Spark_Operator_Instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_depth{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "singlestat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_retries{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "singlestat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_unfinished_work_seconds{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "singlestat",
   "description": "Longest running processor in microseconds",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scheduled_spark_application_controller_longest_running_processor_microseconds{pod=\"$Spark_Operator_Instance\"}"
    }
   ]
  }
 ]
}